Add BE-4 Metholox Engine from DylanSemrau.
KSP-RO/ROEngines pull request #101
Opened 2020-11-07 19:12 UTC by vader111

Add BE-4 Metholox Engine from DylanSemrau.

2020-11-07 19:54 UTC, vader111 commented
Needs https://github.com/KSP-RO/RealismOverhaul/pull/2377

2020-11-10 16:09 UTC, vader111 commented
(Ready To Review)

2020-11-12 02:20 UTC, Capkirk123 commented
Looks good

2020-11-20 16:39 UTC, DRVeyl requested changes

2020-11-20 16:39 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/BE4_DylanSemrau.cfg
> +	breakingTorque = 10000
Make use of ROESetEngineDefaults

2020-11-20 16:39 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/BE4_DylanSemrau.cfg
> +	entryCost = 1
Make use of ROESetEngineDefaults

2020-11-21 19:45 UTC, DRVeyl approved these changes

2020-11-21 20:10 UTC, merged