Add RZ.20
KSP-RO/ROEngines pull request #116
Opened 2020-12-12 00:04 UTC by Capkirk123

Add the RZ.20, a hydrolox upper stage engine created by Rolls-Royce

2021-02-19 17:39 UTC, DRVeyl requested changes
Why are the model files and texture files empty?

2021-02-19 17:39 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/RZ20_Tantares.cfg
> +}
Add newline before EOL

2021-02-20 00:34 UTC, Capkirk123 commented
Strange bug with Github desktop I guess. Renaming everything and then changing it back got it to upload everything properly.

2021-02-20 00:49 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/RZ20_Tantares.cfg
> +	node_attach		  = 0.0,  0.5642, 0.0, 0.0,	1.0, .0
Indenting / last entry should be 0.0?

2021-02-20 16:08 UTC, DRVeyl approved these changes

2021-02-20 16:13 UTC, merged