French Engines
KSP-RO/ROEngines pull request #82
Opened 2020-08-21 05:24 UTC by Capkirk123

Add the Veronique and Viking series of engines.

2020-11-20 16:14 UTC, DRVeyl requested changes

2020-11-20 16:14 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/Viking2_FRE.cfg
> +	breakingTorque = 10000
Can you make use of the tooling ROESetEngineDefaults?

2020-11-20 16:14 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/Viking2_FRE.cfg
> +	childStageOffset = 1
Can you make these parts [and your other PRs] use the tool in https://github.com/KSP-RO/ROEngines/blob/PatchingFixes/GameData/ROEngines/ROEEngineDefaults.cfg?

2020-11-20 16:14 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/Viking4_FRE.cfg
> +	breakingTorque = 10000
Can you make these parts [and your other PRs] use the tool in https://github.com/KSP-RO/ROEngines/blob/PatchingFixes/GameData/ROEngines/ROEEngineDefaults.cfg?

2020-11-20 16:14 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/Viking4_FRE.cfg
> +
Can you make these parts [and your other PRs] use the tool in https://github.com/KSP-RO/ROEngines/blob/PatchingFixes/GameData/ROEngines/ROEEngineDefaults.cfg?

2020-11-20 16:14 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/Viking5_FRE.cfg
> +	breakingTorque = 10000
Can you make these parts [and your other PRs] use the tool in https://github.com/KSP-RO/ROEngines/blob/PatchingFixes/GameData/ROEngines/ROEEngineDefaults.cfg?

2020-11-20 16:14 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/Viking5_FRE.cfg
> +	childStageOffset = 1
Can you make these parts [and your other PRs] use the tool in https://github.com/KSP-RO/ROEngines/blob/PatchingFixes/GameData/ROEngines/ROEEngineDefaults.cfg?

2020-11-20 16:14 UTC, DRVeyl commented on GameData/ROEngines/RealPlume/Vernoique_RE_RealPlume.cfg
> +@PART[ROE-Veronique]:FOR[RealPlume]:NEEDS[SmokeScreen]
:BEFORE[RealPlume] instead of FOR+NEEDS

2020-11-20 16:14 UTC, DRVeyl commented on GameData/ROEngines/RealPlume/Viking2_FRE_RealPlume.cfg
> +@PART[ROE-Viking2]:NEEDS[RealPlume]
BEFORE[RealPlume] instead of running in the default pass

2020-11-20 16:14 UTC, DRVeyl commented on GameData/ROEngines/RealPlume/Viking4_FRE_RealPlume.cfg
> +@PART[ROE-Viking4]:NEEDS[RealPlume]
BEFORE[RealPlume] instead of the default pass

2020-11-20 16:14 UTC, DRVeyl commented on GameData/ROEngines/RealPlume/Viking5_FRE_RealPlume.cfg
> +@PART[ROE-Viking5]:NEEDS[RealPlume]
BEFORE[RealPlume] instead of the default pass?

2020-11-20 16:14 UTC, DRVeyl commented on GameData/ROEngines/RealPlume/Viking5_FRE_RealPlume.cfg
> +}
closing newline

2020-11-20 16:14 UTC, DRVeyl commented on GameData/ROEngines/RealPlume/Viking2_FRE_RealPlume.cfg
> +}
closing newline

2020-11-20 16:14 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/Viking5_FRE.cfg
> +}
closing newline

2020-11-20 16:14 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/Viking4_FRE.cfg
> +}
closing newline

2020-11-20 16:14 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/Viking2_FRE.cfg
> +}
closing newline

2020-11-21 07:04 UTC, Capkirk123 commented on GameData/ROEngines/RealPlume/Viking5_FRE_RealPlume.cfg
> +}
?

2020-11-21 15:18 UTC, DRVeyl approved these changes

2020-11-21 15:19 UTC, merged