Swap F-1 and Cleanup
KSP-RO/ROEngines pull request #83
Opened 2020-08-23 05:57 UTC by Capkirk123

Replace the SSTU F-1 Model with the BDB F-1 model (its better proportioned, and has toggelable insulation)

Remove unused models/textures

Fix improperly configured files for PatchManager

Should resolve https://github.com/KSP-RO/ROEngines/issues/79
(Not tested)

2020-10-18 14:10 UTC, DRVeyl requested changes
Everything else looks good, at least from a static review of the changes.

2020-10-18 14:10 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/F1B_BDB.cfg
> +	breakingTorque = 10000
Can you make use of the tooling `ROESetEngineDefaults` established in #78 ?

2020-10-18 14:10 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/F1B_BDB.cfg
> +	entryCost = 1
`ROESetEngineDefaults` established in #78 ?

2020-10-18 14:10 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/F1_BDB.cfg
> +	breakingTorque = 10000
`ROESetEngineDefaults` established in #78 ?

2020-10-18 14:10 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/F1_BDB.cfg
> +	entryCost = 1
`ROESetEngineDefaults` established in #78 ?

2020-10-18 22:47 UTC, Capkirk123 commented
Defaults set

2020-10-19 05:06 UTC, vader111 commented
@Capkirk123 you still have to remove all the values that the ROESetEngineDefaults sets

2020-10-25 13:31 UTC, DRVeyl approved these changes

2020-11-21 15:47 UTC, merged