Add Atlas V RD-180 from BDB
KSP-RO/ROEngines pull request #95
Opened 2020-11-07 19:10 UTC by vader111

Add Atlas V RD-180 from BDB

2020-11-10 15:33 UTC, vader111 commented
(Ready To Review)

2020-11-11 02:53 UTC, Capkirk123 commented
Surface attaching is disabled for the RD-180 (it should be enabled). Also, I would recommend at least disabling the old RD-180, if not outright replacing it.

2020-11-11 04:58 UTC, vader111 commented
@Capkirk123 Fixed

2020-11-12 01:26 UTC, Capkirk123 commented
Looks good. I might suggest enabling the nozzle internal glow however.

2020-11-12 04:28 UTC, vader111 commented
@Capkirk123 Should be Fixed now

2020-11-15 01:50 UTC, Capkirk123 commented
Everything looks good

2020-11-20 16:04 UTC, DRVeyl requested changes

2020-11-20 16:04 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/RD180_BDB.cfg
> +	breakingTorque = 10000
Can you make these parts [and your other PRs] use the tool in https://github.com/KSP-RO/ROEngines/blob/PatchingFixes/GameData/ROEngines/ROEEngineDefaults.cfg?

2020-11-20 16:04 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/RD180_BDB.cfg
> +	entryCost = 54000
Can you make these parts [and your other PRs] use the tool in https://github.com/KSP-RO/ROEngines/blob/PatchingFixes/GameData/ROEngines/ROEEngineDefaults.cfg?

2020-11-21 19:56 UTC, DRVeyl approved these changes

2020-11-21 19:57 UTC, DRVeyl commented
Can you resolve the conflict?  (Probably a rename or deletion?)

2020-11-22 13:38 UTC, merged