Add RL-10A4-2 & RL10A4-2N from BDB
KSP-RO/ROEngines pull request #96
Opened 2020-11-07 19:10 UTC by vader111

Add RL-10A4-2 & RL10A4-2N from BDB

2020-11-07 19:54 UTC, vader111 commented
Needs KSP-RO/RealismOverhaul#2377

2020-11-10 18:08 UTC, vader111 commented
(Ready To Review)

2020-11-12 04:28 UTC, vader111 commented
@Capkirk123 Should be Fixed now

2020-11-20 21:19 UTC, DRVeyl requested changes

2020-11-20 21:19 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/RL10A4-2N_BDB.cfg
> +	breakingTorque = 10000
Make use of ROESetEngineDefaults

2020-11-20 21:19 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/RL10A4-2N_BDB.cfg
> +	entryCost = 26000
Make use of ROESetEngineDefaults.  RP-1 must be responsible for where in the Tech Tree it ends up.

2020-11-20 21:19 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/RL10A4-2N_BDB.cfg
> +		gimbalResponseSpeed = 16
Believe these values will be overridden by RO's engine config.  Should only set the module and transform in the original part def.  If the gimbal needs to be overrridden, that happens in a later pass.

2020-11-20 21:19 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/RL10A4-2N_BDB.cfg
> +		}
Which CONFIG entry are you editing?  There should be an RL10A-4-1-2 added in RO, and it should get the correct atmosphere curve, and this patch should just delete unwanted engine configs.  I guess this is sort of okay, but it's weird to use the engine config system and then edit it.  Unless there is a specific reason this config should not be in RO.

2020-11-20 21:19 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/RL10A4-2_BDB.cfg
> +	breakingTorque = 10000
Use ROESetEngineDefaults

2020-11-20 21:19 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/RL10A4-2_BDB.cfg
> +	entryCost = 26000
Use ROESetEngineDefaults

2020-11-20 21:19 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/RL10A4-2_BDB.cfg
> +		gimbalResponseSpeed = 16
These are overwritten / configured by RO's engine config?

2020-11-20 21:19 UTC, DRVeyl commented on GameData/ROEngines/PartConfigs/RL10A4-2_BDB.cfg
> +		}
As above, seems this config should become present in RO.  Or why not?

2020-11-22 05:57 UTC, vader111 commented
Will need https://github.com/KSP-RO/RealismOverhaul/pull/2377

2020-11-22 06:43 UTC, vader111 commented
Also Needs https://github.com/KSP-RO/RP-0/pull/1406

2020-11-22 13:44 UTC, DRVeyl approved these changes

2020-11-22 13:55 UTC, merged